
http_port: '8080'
rpc_port: '8081'

wechat:
    appid: 'wxf03281710c7b7006'
    secret: 'e09afa1e82be63284c903d69561111c5'

log:
    dir: './log/'
    suffix: '.log.%Y%m%d'
    cut_days: 1
    file_save_days: 7