// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"tools/apps/wechat/configs"
	"tools/apps/wechat/internal/web/biz"
	"tools/apps/wechat/internal/web/data"
	"tools/apps/wechat/internal/web/server"
	"tools/apps/wechat/internal/web/service"
	"tools/internal/pkg/app"
	"tools/internal/pkg/logger"
	"tools/internal/pkg/wxapi"
)

// Injectors from wire.go:

func initApp(env *string, c *configs.Config, logClient *logger.LogClient) (*app.App, error) {
	wxApiClient := wxapi.NewWxApiClient(c, logClient)
	dataData := data.NewData(wxApiClient)
	userRepo := data.NewUserRepo(dataData)
	userBiz := biz.NewUserBiz(logClient, userRepo)
	messageBiz := biz.NewMessageBiz(logClient, wxApiClient, userBiz)
	massBiz := biz.NewMassBiz(wxApiClient)
	wechatHttpService := service.NewWechatHttpService(logClient, userBiz, messageBiz, massBiz)
	httpServer := server.NewHttpServer(env, c, wechatHttpService)
	appApp := newApp(httpServer)
	return appApp, nil
}
